apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-application
  namespace: argocd
spec:
  project: default 
  source:
    repoURL: https://github.com/LauraOkafor/open-flights.git 
    targetRevision: HEAD
    path: infra  
  destination:
    server: https://kubernetes.default.svc
    namespace: rails-app  # Change to your application namespace
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true