# services:
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   web:
#     build: .
#     entrypoint: /app/entrypoint.web.sh
#     command: bundle exec rails server -p 3000 -b '0.0.0.0'
#     environment:
#       RAILS_ENV: ${RAILS_ENV}
#       DATABASE_HOST: ${DATABASE_HOST}
#       DATABASE_USERNAME: ${DATABASE_USERNAME}
#       DATABASE_PASSWORD: ${DATABASE_PASSWORD}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#       WEBPACKER_DEV_SERVER_HOST: webpacker
#     volumes:
#       - .:/app
#       - node_modules:/app/node_modules
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#       - webpacker

#   webpacker:
#     build: .
#     entrypoint: /app/entrypoint.webpacker.sh
#     command: ./bin/webpack-dev-server
#     environment:
#       RAILS_ENV: ${RAILS_ENV}
#       NODE_ENV: development
#       WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
#     volumes:
#       - .:/app
#       - node_modules:/app/node_modules
#     ports:
#       - "3035:3035"

# volumes:
#   postgres_data:
#   node_modules:


services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    entrypoint: /app/entrypoint.web.sh
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      WEBPACKER_DEV_SERVER_HOST: webpacker
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db: 
        condition: service_healthy
      webpacker:
        condition: service_started

  webpacker:
    build: .
    entrypoint: /app/entrypoint.webpacker.sh
    command: ./bin/webpack-dev-server
    environment:
      RAILS_ENV: ${RAILS_ENV}
      NODE_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3035:3035"

volumes:
  postgres_data:
  node_modules:
